services:
    dbt:
        image: xemuliam/dbt:1.7.8-bigquery1.7.5
        container_name: dbt_container
        environment:
            DBT_PROFILE: aml_profile
            DBT_HOST: postgres_db # Reference to PostgreSQL service
            DBT_USER: postgres_container_user
            DBT_PASSWORD: postgres_container_pass
            DBT_DBNAME: development
            DBT_SCHEMA: public
        volumes:
            - ./risk_engine_dbt:/usr/app # Mount dbt models to container
            - ~/.dbt:/root/.dbt # Ensure profiles are synced
        networks:
            - aml_network

networks:
    aml_network:
        driver: bridge