services:
    dbt:
        image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
        container_name: dbt_runner_container
        environment:
            DBT_PG_HOST: postgres_db # This container_name is discoverable on the shared network
            DBT_PG_PORT: 5432
            DBT_PG_USER: ${DBT_USER}
            DBT_PG_PASS: ${DBT_PASSWORD} # (MUST MATCH main repo's POSTGRES_PASSWORD)
            DBT_PG_DBNAME: ${DBT_DBNAME}
            DBT_PG_SCHEMA: ${DBT_SCHEMA}
            DBT_PROFILES_DIR: /root/.dbt
        volumes:
            - ./risk_engine_dbt:/usr/app/dbt_project
            - ~/.dbt:/root/.dbt
        working_dir: /usr/app/dbt_project # Set the working directory inside the container
        networks:
            - real-time-graph-based-risk-engine_aml_network

networks:
    real-time-graph-based-risk-engine_aml_network:
        external: true